
package services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommandeWS", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommandeWS {


    /**
     * 
     * @param refrepas
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "passerCommande", targetNamespace = "http://services/", className = "services.PasserCommande")
    @ResponseWrapper(localName = "passerCommandeResponse", targetNamespace = "http://services/", className = "services.PasserCommandeResponse")
    @Action(input = "http://services/CommandeWS/passerCommandeRequest", output = "http://services/CommandeWS/passerCommandeResponse")
    public void passerCommande(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String refrepas);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<services.Repas>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulterRepas", targetNamespace = "http://services/", className = "services.ConsulterRepas")
    @ResponseWrapper(localName = "consulterRepasResponse", targetNamespace = "http://services/", className = "services.ConsulterRepasResponse")
    @Action(input = "http://services/CommandeWS/consulterRepasRequest", output = "http://services/CommandeWS/consulterRepasResponse")
    public List<Repas> consulterRepas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
