
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommandeWSService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8080/DS_SOAP/ws/CommandeWS?wsdl")
public class CommandeWSService
    extends Service
{

    private final static URL COMMANDEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMANDEWSSERVICE_EXCEPTION;
    private final static QName COMMANDEWSSERVICE_QNAME = new QName("http://services/", "CommandeWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DS_SOAP/ws/CommandeWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMANDEWSSERVICE_WSDL_LOCATION = url;
        COMMANDEWSSERVICE_EXCEPTION = e;
    }

    public CommandeWSService() {
        super(__getWsdlLocation(), COMMANDEWSSERVICE_QNAME);
    }

    public CommandeWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMANDEWSSERVICE_QNAME, features);
    }

    public CommandeWSService(URL wsdlLocation) {
        super(wsdlLocation, COMMANDEWSSERVICE_QNAME);
    }

    public CommandeWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMANDEWSSERVICE_QNAME, features);
    }

    public CommandeWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommandeWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommandeWS
     */
    @WebEndpoint(name = "CommandeWSPort")
    public CommandeWS getCommandeWSPort() {
        return super.getPort(new QName("http://services/", "CommandeWSPort"), CommandeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommandeWS
     */
    @WebEndpoint(name = "CommandeWSPort")
    public CommandeWS getCommandeWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "CommandeWSPort"), CommandeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMANDEWSSERVICE_EXCEPTION!= null) {
            throw COMMANDEWSSERVICE_EXCEPTION;
        }
        return COMMANDEWSSERVICE_WSDL_LOCATION;
    }

}
